language: node_js

node_js:
  - "8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - npm install -g node-gyp

before_script:
  - node-gyp rebuild

script:
  - node test/test.js
