language: node_js

node_js:
  - "10"
  - "11"
  - "12"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - npm install -g node-gyp

before_script:
  - node-gyp rebuild -C test

script:
  - node test/test.js
